### ISSUE TITLE
New piece set

### ISSUE THREAD

**Issue by CouchTomato87** [mogproject/mog-playground#275]
Hi Mizutani-san, would it be possible to add this piece set as an option?

https://github.com/CouchTomato87/InternationalizedPieces/tree/master/Shogi

FYI, these pieces are also being used on this site: https://pychess-variants.herokuapp.com/

**Comment by mogproject** [comment]
Thanks for your suggestion. But, for now, I'm not willing to include resources under GPL. I'll let you know if I change my mind.

**Comment by CouchTomato87** [comment]
I can always change it (tbh I don't really care about what license it is -- I was just told that I needed one). Is there one that would be more appropriate?

**Comment by mogproject** [comment]
Great to hear that! Either MIT or Apache 2.0 works for me.

**Comment by CouchTomato87** [comment]
Awesome! Would CC work too? I think MIT is more meant for software, and these are just images.

**Comment by mogproject** [comment]
Yes, CC also works perfectly.

**Comment by CouchTomato87** [comment]
Alright, I switched it over :)

I also updated my repository (at least the key files -- not the readme). The most updated version of the set in plastic form is here: https://github.com/CouchTomato87/InternationalizedPieces/tree/master/Shogi/Plastic

And the corresponding wooden versions are here: https://github.com/CouchTomato87/InternationalizedPieces/tree/master/Shogi/Wood

These are also used at www.pychess.org -- although the plastic pieces I have in my repo are more updated with a more 3D look (and I also made each piece just two colors instead of up to 3)

**Comment by mogproject** [comment]
Now, you should be able to choose International 1 and 2 piece sets. Currently, Shogi Playground doesn't distinguish Gyoku from Ou. So, GY images are not used.

Please let me know if you find any other problem. Thanks for your contribution!

**Comment by CouchTomato87** [comment]
Awesome, thanks a lot! I forgot about only one king being used. The only modification I would make is the wooden (International 2) set kings then. The kings there have black/white stripes to distinguish sente and gote. But it looks awkward if there are two with white stripes. So I attached images of kings without stripes.

[OU.zip](https://github.com/mogproject/mog-playground/files/4751876/OU.zip)

Also, isn't the king generically referred to as 玉 rather than 王 in Japanese? So why is 王 used here? Just wondering out of curiosity  :)

**Comment by mogproject** [comment]
Thank you! I will replace the images with new ones.

> So why is 王 used here? Just wondering out of curiosity :)

I basically follow the traditional CSA format (http://www2.computer-shogi.org/wcsc12/record_e.html), where King is denoted by OU.

**Comment by CouchTomato87** [comment]
Thanks! Also I just realized that it isn't available on Shogi Playground Live -- would that be possible as well?
